### ISSUE TITLE
splitSignature - Undeclared identifier

### ISSUE THREAD

**Issue by jack75015** [violetprotocol/ERC1238-token#16]
Hello
I cloned the project and followed the step.
For the compile step `yarn compile`, I got this error:

```
Downloading compiler 0.8.9
Compiling 21 files with 0.8.9
DeclarationError: Undeclared identifier.
  --> contracts/mocks/ERC1238ExpirableMock.sol:52:51:
   |
52 |                 (bytes32 r, bytes32 s, uint8 v) = splitSignature(data[i]);
   |                                                   ^^^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
```

Am i the only one?

**Comment by westbrook-ai** [comment]
I ran into the same error. I don't think I'm going to need that mock anyways, so I just changed its extension from `.sol` to `.badsol` for now, and compiling worked fine. 

Here was the stack trace in case it's helpful to maintainers:
```HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/builtin-tasks/compile.ts:471:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Environment._runTaskDefinition (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at async OverriddenTaskDefinition._action (/Users/0xthresh/Web3/ERC1238-token/node_modules/@typechain/hardhat/src/index.ts:30:30)
    at async Environment._runTaskDefinition (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at async Environment.run (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at async SimpleTaskDefinition.action (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/builtin-tasks/compile.ts:1346:63)
    at async Environment._runTaskDefinition (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at async Environment.run (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at async SimpleTaskDefinition.action (/Users/0xthresh/Web3/ERC1238-token/node_modules/hardhat/src/builtin-tasks/compile.ts:1426:7)```
